### ISSUE TITLE
Good Job!

### ISSUE THREAD

**Issue by amaruk** [ankesreich/eInkDisplayDriver#1]
Hi Anke,

I read your e-ink display project in MagPi Issue 77. Looks amazing!
I have a very old Waveshare 4.3inch e-Paper, which is driven via serial port. [My C++ driver repository.](https://github.com/amaruk/MyEPaperCpp)
I believe your e-ink display devices are driven via SPI ports, right? Maybe it's time for me to get a modern one from Waveshare.
I'm thinking about making a weather forecast device with Pi and the e-ink display. Would you mind sharing some information about how you get weather data in Pi?

Sincere Yours,
Amaruk

**Comment by ankesreich** [comment]
Dear Amaruk,
thank you :)
Yes the e-ink displays are driven by SPI protocol. OpenWeatherMap provides a free api, most other weather providers are not free. I stored the weather information in database to make sure to have weather information if there is no connection to the internet.
All the best for you and your project, Anke

**Comment by amaruk** [comment]
Hmmm, I see.
Thank you so much for the hint! :)
